version: "3"
services:
#  api:
#    build: 
#      context: ./
#    ports:
#      - "3000:4000"
#    container_name: api

  client:
    build: ./
    ports:
      - "4000:3000"
      - "8000:9999"
    container_name: main